# Generated by Django 6.0.1 on 2026-02-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('customer_city', models.CharField(max_length=50)),
                ('customer_date', models.DateTimeField(auto_now_add=True)),
                ('cus_quantity', models.IntegerField(default=0)),
                ('remark', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('truck_no', models.CharField(max_length=50)),
                ('ref_party', models.CharField(max_length=255)),
            ],
        ),
    ]
