# Generated by Django 4.2.11 on 2026-02-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_city',
            new_name='customer_city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_date',
            new_name='customer_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mark',
        ),
    ]
