# Generated by Django 6.0.1 on 2026-02-18 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=255)),
                ('design', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('punch_name', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_quantity', models.IntegerField(default=0)),
                ('std_quantity', models.IntegerField(default=0)),
                ('com_quantity', models.IntegerField(default=0)),
                ('eco_quantity', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
