# Generated by Django 6.0.1 on 2026-02-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_date', models.DateField(auto_now_add=True)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('total_weight', models.FloatField()),
                ('delivery_type', models.CharField(choices=[('full', 'FULL'), ('partial', 'PARTIAL')], default='full', max_length=50)),
                ('status', models.CharField(choices=[('in-transit', 'In-Transit'), ('delivered', 'Delivered')], default='in-transit', max_length=50)),
                ('invoice_number', models.CharField(max_length=500)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_quantity', models.IntegerField(default=0)),
                ('std_quantity', models.IntegerField(default=0)),
                ('com_quantity', models.IntegerField(default=0)),
                ('eco_quantity', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField()),
                ('dispatch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.dispatch')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
