# Generated by Django 6.0.1 on 2026-02-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('catagory', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('ref_party', models.CharField(max_length=255)),
                ('order_type', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(max_length=255)),
                ('mrp_zone', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('pre_quantity', models.IntegerField(default=0)),
                ('std_quantity', models.IntegerField(default=0)),
                ('com_quantity', models.IntegerField(default=0)),
                ('eco_quantity', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('cust_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
