# Generated by Django 4.2.27 on 2026-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allocated_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
