# Generated by Django 4.2.11 on 2026-02-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invioce_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
