# Generated by Django 4.2.11 on 2026-02-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_invioce_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invioce_no',
            new_name='invoice_no',
        ),
    ]
