# Generated by Django 4.2.27 on 2026-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_allocated_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allocation_locked',
            field=models.BooleanField(default=False),
        ),
    ]
