# Generated by Django 4.2.11 on 2026-02-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_invioce_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quan',
        ),
    ]
