# Generated by Django 4.2.11 on 2026-02-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_invioce_no_order_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
