# Generated by Django 4.2.11 on 2026-02-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('customer', '0002_rename_customer_city_customer_customer_city_and_more'),
        ('order', '0003_remove_order_quan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_quentity',
            new_name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pro_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='punch_name',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cust_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
